Adding Home task 6 with txt files
polisvv/DQE_Python pull request #5
Opened 2022-10-30 19:38 UTC by polisvv

2022-11-01 10:20 UTC, romkabauer requested changes

2022-11-01 10:20 UTC, romkabauer commented on normalization/__init__.py
> +import re
Common practice is to leave `__init__.py` empty in most cases. `__init__.py` content is usually used for some initialization processes if some specific class or function of the module needs to be set up.

I recommend adding normalization.py file inside this folder or import directly from files with previous homework.

More on this: https://docs.python.org/3/tutorial/modules.html#packages

2022-11-01 10:20 UTC, romkabauer commented on HT6_2.py
> +        txt_file_list = []
TO REVIEW:

[file for file in os.listdir() if file.endswith(".txt")]

2022-11-01 10:20 UTC, romkabauer commented on HT6_2.py
> +pub_method = pub.get_publication_method()
Suggest to use class properties to simplify the logic for user of these module.
Examples sent to teams chat

2022-11-01 10:20 UTC, romkabauer commented on HT6_2.py
> +if pub_method == "txt":
I recommend to remove file based on file_name object existance, because with this condition `file_name` variable can be undefined in case if previous condition above (checking `pub_method`) will be skipped

Suggestion:
`if file_name:
    os.remove(file_name)
    print(...)`

2022-11-01 10:20 UTC, romkabauer commented on HT6_2.py
> +        while True:
The loop will be executed 1 time in any case, it can be removed to save cpu resources

2022-11-01 10:20 UTC, romkabauer commented on HT6_2.py
> +            if self.is_valid_publication_method(publication_method):
Function `is_valid_publication_method` is actually not necessary from my point of view.
You will get the same result doing:
`if publication_method == "1":
     return "txt"
 elif publication_method == "2":
     return "cli"
 else:
     print('Invalid publication method')
     print("Wrong format. Please try again or Ctrl+C to exit.")`

2022-11-01 10:20 UTC, romkabauer commented on HT6_2.py
> +        if publication.publication_type == "News":
String type does not have property publication_type. I believe you mean publication argument should be of your own class type. I recommend creating parent class `Publication` with property `publication_type` and make `News, Ad, Joke` its children.

2022-11-02 22:59 UTC, polisvv commented on normalization/__init__.py
> +import re
done

2022-11-02 22:59 UTC, polisvv commented on HT6_2.py
> +        txt_file_list = []
done

2022-11-02 22:59 UTC, polisvv commented on HT6_2.py
> +if pub_method == "txt":
Could you please explain, I don't understand your point. Why this condition can be skipped? If pub_method != "txt", there is no file to delete

2022-11-02 22:59 UTC, polisvv commented on HT6_2.py
> +        while True:
I am trying, but getting an error without loop if file name is not exist

2022-11-02 22:59 UTC, polisvv commented on HT6_2.py
> +            if self.is_valid_publication_method(publication_method):
done

2022-11-02 23:08 UTC, polisvv commented on HT6_2.py
> +        if publication.publication_type == "News":
I don't understand this comment as well...

2022-11-09 07:29 UTC, romkabauer requested changes

2022-11-09 07:29 UTC, romkabauer commented on HT6_3.py
> +    def get_news_location(self):
I believe it is @staticmethod :) It is not referring to the object (self) inside the method

2022-11-09 07:29 UTC, romkabauer commented on HT6_3.py
> +    def get_due_date(self):
I believe it is @staticmethod :)

2022-11-09 07:29 UTC, romkabauer commented on HT6_3.py
> +    def __init__(self, publication_type, publication_body:str ="", funny_meter: str = "") -> None:
Don't forget to use Ctrl+Alt+L for formating:)

2022-11-09 07:29 UTC, romkabauer commented on HT6_3.py
> +    def generate_random_funny_meter(self):
I believe it is @staticmethod :)

2022-11-09 07:29 UTC, romkabauer commented on HT6_3.py
> +    def __is_valid_publication_type(self, publication_type):
I believe it is @staticmethod :)

2022-11-09 07:29 UTC, romkabauer commented on HT6_3.py
> +    def get_publication_text(self):
I believe it is @staticmethod :)

2022-11-09 07:29 UTC, romkabauer commented on HT6_3.py
> +    def get_publication_specific_info(self, publication: Publication) -> str:
This function is returning None instead of string as I see

2022-11-09 07:29 UTC, romkabauer commented on HT6_3.py
> +            publication.location = publication.get_news_location()
Actually, if you are referring to the functions of the child classes in the method, it is better to refer to typing.Union[News,Ad,Joke,OtherChildClass] in the signature

2022-11-09 07:29 UTC, romkabauer commented on HT6_3.py
> +            publication.funny_meter = publication.generate_random_funny_meter()
The same recommendation here:
if you are referring to the functions of the child classes in the method, it is better to refer to typing.Union[News,Ad,Joke,OtherChildClass] in the signature

2022-11-15 08:59 UTC, romkabauer approved these changes

2022-11-15 08:59 UTC, romkabauer commented on HT6_3.py
> +        super().__init__(publication_type=publication_type, publication_body=publication_body)
TO REVIEW:
I think it is worth to not provide publication type while creating object of the class, let's just assign certain pub type

class News(Publication):
    def __init__(self, publish_datetime, publication_body: str = "", location: str = "") -> None:
        super().__init__(publication_type="News", publication_body=publication_body)
.....

2022-11-15 08:59 UTC, romkabauer commented on HT6_3.py
> +        super().__init__(publication_type=publication_type, publication_body=publication_body)
The same for Ad and Joke

2022-11-15 08:59 UTC, romkabauer commented on HT6_3.py
> +            return publication.location
TO REVIEW: 
I think it is redundant. Moreover the function should return None, not str

2022-11-18 17:08 UTC, merged